# Generated by Django 4.2.2 on 2023-06-22 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('inside', models.BooleanField(default=False)),
                ('outside', models.BooleanField(default=False)),
                ('solo', models.BooleanField(default=False)),
                ('group', models.BooleanField(default=False)),
                ('extreme', models.BooleanField(default=False)),
                ('calm', models.BooleanField(default=False)),
                ('focus', models.BooleanField(default=False)),
                ('achievement', models.BooleanField(default=False)),
                ('bodyhealth', models.BooleanField(default=False)),
                ('confidence', models.BooleanField(default=False)),
                ('mental', models.BooleanField(default=False)),
                ('short', models.BooleanField(default=False)),
                ('newtry', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
