# Generated by Django 4.2.2 on 2023-06-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_tag_delete_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_tag',
            new_name='UserTag',
        ),
    ]
