# Generated by Django 4.2.2 on 2023-07-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_password'),
        ('user', '0006_alter_user_survey_result_count'),
    ]

    operations = [
    ]
