# Generated by Django 4.2.2 on 2023-06-30 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_score'),
        ('user', '0007_merge_20230630_0002'),
    ]

    operations = [
    ]
