# Generated by Django 4.2.2 on 2023-06-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, unique=True)),
                ('birth', models.IntegerField(default=0, null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
