# Generated by Django 4.2.2 on 2023-06-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_user_alter_account_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
