# Generated by Django 4.2.2 on 2023-06-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('effect', models.TextField()),
                ('recommnad', models.TextField()),
            ],
            options={
                'db_table': 'challenge',
            },
        ),
    ]
