# Generated by Django 4.2.2 on 2023-06-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.ImageField(default='images/challenge/Tom.gif', upload_to='images/challenge'),
        ),
    ]
