# Generated by Django 4.2.2 on 2023-06-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_challenge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='sub_effect',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
