# Generated by Django 4.2.2 on 2023-06-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_challenge_sub_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(upload_to='images/challenge'),
        ),
    ]
