# Generated by Django 4.2.2 on 2023-06-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_rename_recommnad_challenge_recommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('inside', models.BooleanField(default=False)),
                ('outside', models.BooleanField(default=False)),
                ('solo', models.BooleanField(default=False)),
                ('group', models.BooleanField(default=False)),
                ('pay', models.BooleanField(default=False)),
                ('free', models.BooleanField(default=False)),
                ('static', models.BooleanField(default=False)),
                ('dynamic', models.BooleanField(default=False)),
                ('relaxation', models.BooleanField(default=False)),
                ('immunity', models.BooleanField(default=False)),
                ('easy', models.BooleanField(default=False)),
                ('sleep', models.BooleanField(default=False)),
                ('circulation', models.BooleanField(default=False)),
                ('muscle', models.BooleanField(default=False)),
                ('stability', models.BooleanField(default=False)),
                ('concentration', models.BooleanField(default=False)),
                ('creativity', models.BooleanField(default=False)),
                ('satisfaction', models.BooleanField(default=False)),
                ('achievement', models.BooleanField(default=False)),
                ('depression', models.BooleanField(default=False)),
                ('selfesteem', models.BooleanField(default=False)),
                ('organization', models.BooleanField(default=False)),
                ('expression', models.BooleanField(default=False)),
                ('precision', models.BooleanField(default=False)),
                ('easylearn', models.BooleanField(default=False)),
                ('dexterity', models.BooleanField(default=False)),
                ('motor', models.BooleanField(default=False)),
                ('memory', models.BooleanField(default=False)),
                ('skeletal', models.BooleanField(default=False)),
                ('balance', models.BooleanField(default=False)),
                ('flexibility', models.BooleanField(default=False)),
                ('sociability', models.BooleanField(default=False)),
                ('cooperation', models.BooleanField(default=False)),
                ('bloodpressure', models.BooleanField(default=False)),
                ('problemsolving', models.BooleanField(default=False)),
                ('innerpeace', models.BooleanField(default=False)),
                ('positive', models.BooleanField(default=False)),
                ('mood', models.BooleanField(default=False)),
                ('anxiety', models.BooleanField(default=False)),
                ('bedtime', models.BooleanField(default=False)),
                ('socialrelationship', models.BooleanField(default=False)),
                ('newchallenge', models.BooleanField(default=False)),
                ('friends', models.BooleanField(default=False)),
                ('awareness', models.BooleanField(default=False)),
                ('challengename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge', unique=True)),
            ],
        ),
    ]
