# Generated by Django 4.2.2 on 2023-06-24 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0006_rename_recommnad_challenge_recommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participaint',
            },
        ),
        migrations.CreateModel(
            name='Challenge_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.BooleanField(default=False, verbose_name='아침')),
                ('afternoon', models.BooleanField(default=False, verbose_name='점심')),
                ('evening', models.BooleanField(default=False, verbose_name='저녁')),
                ('inside', models.BooleanField(default=False, verbose_name='실내')),
                ('outside', models.BooleanField(default=False, verbose_name='실외')),
                ('solo', models.BooleanField(default=False, verbose_name='혼자')),
                ('group', models.BooleanField(default=False, verbose_name='여럿이')),
                ('pay', models.BooleanField(default=False, verbose_name='유료')),
                ('free', models.BooleanField(default=False, verbose_name='무료')),
                ('static', models.BooleanField(default=False, verbose_name='정적인')),
                ('dynamic', models.BooleanField(default=False, verbose_name='동적인')),
                ('relaxation', models.BooleanField(default=False, verbose_name='피로해소')),
                ('immunity', models.BooleanField(default=False, verbose_name='면역력 향상')),
                ('easy', models.BooleanField(default=False, verbose_name='누구나 쉽게')),
                ('sleep', models.BooleanField(default=False, verbose_name='수면 개선')),
                ('circulation', models.BooleanField(default=False, verbose_name='혈액순환 촉진')),
                ('muscle', models.BooleanField(default=False, verbose_name='근육이완')),
                ('stability', models.BooleanField(default=False, verbose_name='정서 안정')),
                ('concentration', models.BooleanField(default=False, verbose_name='집중력 향상')),
                ('creativity', models.BooleanField(default=False, verbose_name='창의력 발휘')),
                ('satisfaction', models.BooleanField(default=False, verbose_name='만족감 증진')),
                ('achievement', models.BooleanField(default=False, verbose_name='성취감')),
                ('depression', models.BooleanField(default=False, verbose_name='우울감 개선')),
                ('selfesteem', models.BooleanField(default=False, verbose_name='자아존중감 형성')),
                ('organization', models.BooleanField(default=False, verbose_name='감정 정리')),
                ('expression', models.BooleanField(default=False, verbose_name='표현력 향상')),
                ('precision', models.BooleanField(default=False, verbose_name='꼼꼼함 향상')),
                ('easylearn', models.BooleanField(default=False, verbose_name='배우기 쉬운')),
                ('dexterity', models.BooleanField(default=False, verbose_name='손재주 향상')),
                ('motor', models.BooleanField(default=False, verbose_name='미세 운동 능력 발달')),
                ('memory', models.BooleanField(default=False, verbose_name='기억력 향상')),
                ('skeletal', models.BooleanField(default=False, verbose_name='근육과 골격 강화')),
                ('balance', models.BooleanField(default=False, verbose_name='균형감각 향상')),
                ('flexibility', models.BooleanField(default=False, verbose_name='유연성 향상')),
                ('sociability', models.BooleanField(default=False, verbose_name='사회성 향상')),
                ('cooperation', models.BooleanField(default=False, verbose_name='협동성 향상')),
                ('bloodpressure', models.BooleanField(default=False, verbose_name='혈압 낮춤')),
                ('problemsolving', models.BooleanField(default=False, verbose_name='문제 해결 능력 향상')),
                ('innerpeace', models.BooleanField(default=False, verbose_name='마음 진정')),
                ('positive', models.BooleanField(default=False, verbose_name='긍정적인 생각')),
                ('mood', models.BooleanField(default=False, verbose_name='기분 전환')),
                ('anxiety', models.BooleanField(default=False, verbose_name='불안 해소')),
                ('bedtime', models.BooleanField(default=False, verbose_name='취침 전')),
                ('socialrelationship', models.BooleanField(default=False, verbose_name='사회적 관계 개선')),
                ('newchallenge', models.BooleanField(default=False, verbose_name='새로운 도전')),
                ('friends', models.BooleanField(default=False, verbose_name='친구와 함께')),
                ('awareness', models.BooleanField(default=False, verbose_name='도전 의식')),
                ('confidence', models.BooleanField(default=False, verbose_name='자신감')),
                ('output', models.BooleanField(default=False, verbose_name='산출물')),
                ('challengename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge', unique=True)),
            ],
            options={
                'db_table': 'challenge_tag',
            },
        ),
    ]
