# Generated by Django 4.2.2 on 2023-06-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_challenge_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge_tag',
            name='achievement',
            field=models.BooleanField(default=False, verbose_name='성취감'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='afternoon',
            field=models.BooleanField(default=False, verbose_name='점심'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='anxiety',
            field=models.BooleanField(default=False, verbose_name='불안 해소'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='awareness',
            field=models.BooleanField(default=False, verbose_name='도전 의식'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='balance',
            field=models.BooleanField(default=False, verbose_name='균형감각 향상'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='bedtime',
            field=models.BooleanField(default=False, verbose_name='취침 전'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='bloodpressure',
            field=models.BooleanField(default=False, verbose_name='혈압 낮춤'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='circulation',
            field=models.BooleanField(default=False, verbose_name='혈액순환 촉진'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='concentration',
            field=models.BooleanField(default=False, verbose_name='집중력 향상'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='cooperation',
            field=models.BooleanField(default=False, verbose_name='협동성 향상'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='creativity',
            field=models.BooleanField(default=False, verbose_name='창의력 발휘'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='depression',
            field=models.BooleanField(default=False, verbose_name='우울감 개선'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='dexterity',
            field=models.BooleanField(default=False, verbose_name='손재주 향상'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='dynamic',
            field=models.BooleanField(default=False, verbose_name='동적인'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='easy',
            field=models.BooleanField(default=False, verbose_name='누구나 쉽게'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='easylearn',
            field=models.BooleanField(default=False, verbose_name='배우기 쉬운'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='evening',
            field=models.BooleanField(default=False, verbose_name='저녁'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='expression',
            field=models.BooleanField(default=False, verbose_name='표현력 향상'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='flexibility',
            field=models.BooleanField(default=False, verbose_name='유연성 향상'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='free',
            field=models.BooleanField(default=False, verbose_name='무료'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='friends',
            field=models.BooleanField(default=False, verbose_name='친구와 함께'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='group',
            field=models.BooleanField(default=False, verbose_name='여럿이'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='immunity',
            field=models.BooleanField(default=False, verbose_name='면역력 향상'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='innerpeace',
            field=models.BooleanField(default=False, verbose_name='마음 진정'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='inside',
            field=models.BooleanField(default=False, verbose_name='실내'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='memory',
            field=models.BooleanField(default=False, verbose_name='기억력 향상'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='mood',
            field=models.BooleanField(default=False, verbose_name='기분 전환'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='morning',
            field=models.BooleanField(default=False, verbose_name='아침'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='motor',
            field=models.BooleanField(default=False, verbose_name='미세 운동 능력 발달'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='muscle',
            field=models.BooleanField(default=False, verbose_name='근육이완'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='newchallenge',
            field=models.BooleanField(default=False, verbose_name='새로운 도전'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='organization',
            field=models.BooleanField(default=False, verbose_name='감정 정리'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='outside',
            field=models.BooleanField(default=False, verbose_name='실외'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='pay',
            field=models.BooleanField(default=False, verbose_name='유료'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='positive',
            field=models.BooleanField(default=False, verbose_name='긍정적인 생각'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='precision',
            field=models.BooleanField(default=False, verbose_name='꼼꼼함 향상'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='problemsolving',
            field=models.BooleanField(default=False, verbose_name='문제 해결 능력 향상'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='relaxation',
            field=models.BooleanField(default=False, verbose_name='피로해소'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='satisfaction',
            field=models.BooleanField(default=False, verbose_name='만족감 증진'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='selfesteem',
            field=models.BooleanField(default=False, verbose_name='자아존중감 형성'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='skeletal',
            field=models.BooleanField(default=False, verbose_name='근육과 골격 강화'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='sleep',
            field=models.BooleanField(default=False, verbose_name='수면 개선'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='sociability',
            field=models.BooleanField(default=False, verbose_name='사회성 향상'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='socialrelationship',
            field=models.BooleanField(default=False, verbose_name='사회적 관계 개선'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='solo',
            field=models.BooleanField(default=False, verbose_name='혼자'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='stability',
            field=models.BooleanField(default=False, verbose_name='정서 안정'),
        ),
        migrations.AlterField(
            model_name='challenge_tag',
            name='static',
            field=models.BooleanField(default=False, verbose_name='정적인'),
        ),
    ]
