# Generated by Django 4.2.2 on 2023-06-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_participant_challenge_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Challenge_tag',
            new_name='ChallengeTag',
        ),
        migrations.AlterModelTable(
            name='challengetag',
            table='challengeTag',
        ),
    ]
