# Generated by Django 4.2.2 on 2023-06-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_rename_challenge_tag_challengetag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengetag',
            old_name='challengename',
            new_name='challenge',
        ),
    ]
