# Generated by Django 4.2.2 on 2023-06-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_rename_challengename_challengetag_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='challenge.challenge'),
        ),
    ]
