# Generated by Django 4.2.2 on 2023-06-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_alter_participant_challenge'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participant',
            table='participant',
        ),
    ]
