# Generated by Django 4.2.2 on 2023-06-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        ('community', '0002_rename_post_article'),
    ]

    operations = [
    ]
