# Generated by Django 4.2.2 on 2023-06-28 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_alter_participant_table'),
        ('community', '0004_article_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge'),
        ),
    ]
