# Generated by Django 4.2.2 on 2023-06-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_article_like_users_like'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table=None,
        ),
    ]
