# Generated by Django 4.2.2 on 2023-06-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
