# Generated by Django 4.2.2 on 2023-06-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        ('community', '0005_remove_article_content_remove_article_title'),
    ]

    operations = [
    ]
