# Generated by Django 4.2.2 on 2023-06-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_article_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
