# Generated by Django 4.2.2 on 2023-06-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_remove_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='challenge',
        ),
    ]
