# Generated by Django 4.2.2 on 2023-06-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_article_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_score',
            field=models.IntegerField(default=0),
        ),
    ]
